CREATE ROLE IF NOT EXISTS APP_CLONER_ROLE;
CREATE DATABASE IF NOT EXISTS STREAMLIT_APPS_DB;
CREATE WAREHOUSE IF NOT EXISTS STREAMLIT_WH 
    WAREHOUSE_SIZE = 'XSMALL' 
    WAREHOUSE_TYPE = 'STANDARD'
    AUTO_SUSPEND = 300 
    AUTO_RESUME = TRUE 
    INITIALLY_SUSPENDED = TRUE;

USE DATABASE STREAMLIT_APPS_DB;
CREATE SCHEMA IF NOT EXISTS PUBLIC;


GRANT USAGE ON WAREHOUSE STREAMLIT_WH TO ROLE APP_CLONER_ROLE;
GRANT CREATE DATABASE ON ACCOUNT TO ROLE APP_CLONER_ROLE;
GRANT USAGE ON DATABASE STREAMLIT_APPS_DB TO ROLE APP_CLONER_ROLE;
GRANT CREATE STREAMLIT ON SCHEMA STREAMLIT_APPS_DB.PUBLIC TO ROLE APP_CLONER_ROLE;

CREATE ROLE IF NOT EXISTS DEVELOPER_ROLE;
CREATE ROLE IF NOT EXISTS READONLY_ROLE;


